import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBezierCurve,
  faBook,
  faCheck,
  faChevronLeft,
  faClock,
  faDatabase,
  faEyeDropper,
  faFire,
  faHeart as fasHeart,
  faMinus,
  faMinusSquare,
  faPenSquare,
  faPlus,
  faPlusSquare,
  faTachometerAlt,
  faTimes,
  faTimesCircle,
  faStar as fasStar,
  faStickyNote,
  faSync,
  faUser,
  faUsers,
  faUsersCog,
  faUserShield,
  faCity,
  faGlobe,
  faInfoCircle
} from '@fortawesome/free-solid-svg-icons';
import {
  faCheckSquare,
  faHeart as farHeart,
  faStar as farStar,
  faSquare
} from '@fortawesome/free-regular-svg-icons';

library.add(
  faBezierCurve,
  faBook,
  faCheck,
  faCheckSquare,
  faChevronLeft,
  faClock,
  faDatabase,
  faEyeDropper,
  faFire,
  faCity,
  faGlobe,
  faInfoCircle,
  fasHeart,
  farHeart,
  faMinus,
  faMinusSquare,
  faPenSquare,
  faPlus,
  faPlusSquare,
  fasStar,
  farStar,
  faSquare,
  faStickyNote,
  faSync,
  faTachometerAlt,
  faTimes,
  faTimesCircle,
  faUser,
  faUsers,
  faUsersCog,
  faUserShield
);

export default library;
